python run_lquad.py \
    --model_type bert \
    --model_name_or_path bert-base-cased \
    --do_train \
    --do_eval \
    --do_lower_case \
    --train_file lquad/train.json \
    --predict_file lquad/dev.json \
    --per_gpu_train_batch_size 12 \
    --learning_rate 3e-5 \
    --num_train_epochs 5.0 \
    --max_seq_length 384 \
    --doc_stride 128 \
    --output_dir output
