python finetune_rag.py \
    --data_dir ./trainingSet \
    --output_dir ./ragOutput \
    --model_name_or_path facebook/rag-sequence-base \
    --model_type rag_sequence \
    --fp16 \
    --gpus 1 \
    --index_name custom \
    --passages_path ./parsedDataset/my_knowledge_dataset \
    --index_path ./parsedDataset/my_knowledge_dataset_hnsw_index.faiss \
    --do_train \
    --do_predict \
    --n_val -1 \
    --val_check_interval 1.0 \
    --train_batch_size 2 \
    --eval_batch_size 1 \
    --max_source_length 25 \
    --max_target_length 25 \
    --val_max_target_length 25 \
    --test_max_target_length 25 \
    --label_smoothing 0.1 \
    --dropout 0.1 \
    --attention_dropout 0.1 \
    --weight_decay 0.001 \
    --adam_epsilon 1e-08 \
    --max_grad_norm 0.1 \
    --lr_scheduler polynomial \
    --learning_rate 3e-04 \
    --num_train_epochs 1 \
    --warmup_steps 4 \
    --gradient_accumulation_steps 1 \
    --use_dummy_dataset 1